### ISSUE TITLE
Shopware 6.6.3 Incompatibility? 

### ISSUE THREAD

**Issue by haupt-pascal** [shopware/SwagExtensionStore#15]
Good Morning! 

After an update of a customer to Shopware 6.6.3, there is a continuous error on the part of the Shopware backend which results in a 500 error and could only be fixed by deactivating the plugin: 

`In Loader.php line 68:
  Cannot load resource “/home/XXXXXXX/staging/custom/plugins/SwagExtensionStore/src/Controller/DataController.php”. Make sure there is a
  loader supporting the “annotation” type.`

Log: 
`An exception has been thrown during the rendering of a template (\"Cannot load resource \"/home/XXXXXX
/staging/custom/plugins/SwagExtensionStore/src/Controller/DataController.php\". Make sure there is a loader supporting the \"annotation\" typ
e.\"). at /home/XXXXXXX/staging/vendor/shopware/storefront/Resources/views/storefront/layout/meta.html.twig:154)\n[previous exception] [obje
ct] (Symfony\\Component\\Config\\Exception\\LoaderLoadException(code: 0): Cannot load resource \"/home/XXXXXX/staging/custom/plugins/SwagEx
tensionStore/src/Controller/DataController.php\". Make sure there is a loader supporting the \"annotation\" type. at /home/XXXXXX/staging/v
endor/symfony/config/Loader/Loader.php:68)"} []`

Is this possibly an incompatibility between the current Shopware SwagExtensionStore and Shopware 6.6.3?

**Comment by mstegmeyer** [comment]
Maybe you need to update the Store to Version 3.x?

**Comment by haupt-pascal** [comment]
The store is already at the latest possible version, still causing the error.

**Comment by mstegmeyer** [comment]
We can't reproduce this. Have you tried clearing your cache, reinstalling the plugin (with a deletion of the plugin folder) and possibly also restarting your webserver? You seem to be using old versions of files.

**Comment by ghost** [comment]
i have similar issue here
